### ISSUE TITLE
Bare except

### ISSUE THREAD

**Issue by llchan** [long2ice/asynch#117]
The comment makes it seem like this bare `except:` is intentional, but I'm wondering why?  If a `SIGTERM`/`SIGINT` arrives this will absorb it and behave imho unexpectedly.  I suspect the actual intent is to do a `except Exception:` so that `SystemExit` and `KeyboardInterrupt` behave normally.

https://github.com/long2ice/asynch/blob/9d80d725ec5e142bfb9d088a86d85dcfeb367edc/asynch/cursors.py#L144

**Comment by stankudrow** [comment]
Hello, a PR is welcome, @llchan , do you want to open it? Perhaps a more specific exception is suitable for this case.

**Comment by stankudrow** [comment]
@llchan , you can close this issue, the work is done and is available in the `asynch v0.2.5`.
