### ISSUE TITLE
Connection pool with predefined connections

### ISSUE THREAD

**Issue by ghuname** [long2ice/asynch#3]
Let's say that I have cluster of 6 nodes.
I would like to create a connection pool with 6 connections, one per each node.

Can I implement such behavior with asynch.create_pool()?

**Comment by long2ice** [comment]
current not support

**Comment by ghuname** [comment]
In example you have provided:

```
async def use_pool():
    pool = await asynch.create_pool()
    async with pool.acquire() as conn:
        async with conn.cursor() as cursor:
            await cursor.execute("SELECT 1")
            ret = cursor.fetchone()
            assert ret == (1,)
    pool.close()
    await pool.wait_closed()
```

where connection parameters should be specified (host, port, database...)?

If I understood correctly, I should create a global pool object and afterwards,  whenever I want to query database, I should use:

```
async with pool.acquire() as conn:
        async with conn.cursor() as cursor:
            await cursor.execute("SELECT 1")
            ret = cursor.fetchone()
``` 

Can you please confirm?

**Comment by long2ice** [comment]
params pass in create_pool

**Comment by ghuname** [comment]
Maybe you should update the example.
