### ISSUE TITLE
Compressed = True does not work

### ISSUE THREAD

**Issue by denisov-vlad** [long2ice/asynch#36]
Hi!

Compression doesn't work in `asynch` while the same settings in `clickhouse-driver` works.

**Comment by denisov-vlad** [comment]
@long2ice thanks!

Now I have `asynch.errors.PartiallyConsumedQueryError: Simultaneous queries on single connection detected` with compression=True option.

I use `asynch.create_pool()` for connection.

**Comment by long2ice** [comment]
Show me the code

**Comment by denisov-vlad** [comment]
That's from FastAPI based application:


Config:

```yaml
  host: removed
  port: 9440
  user: removed
  password: removed
  database: removed
  secure: True
  ca_certs: removed
  compression: True
```

Code:

```python
from fastapi import FastAPI
import asynch


application = FastAPI()

@application.on_event("startup")
async def setup():
    clickhouse_config = config["clickhouse"]
    # del clickhouse_config["compression"]
    application.state.ch = await asynch.create_pool(**config["clickhouse"])

@application.get("/")
async def proba():
    clickhouse_status = False
    async with application.state.ch.acquire() as conn:
        async with conn.cursor() as cursor:
            await cursor.execute("SELECT 1")
            result = cursor.fetchone()
            if result is not None and result[0] == 1:
                clickhouse_status = True
    return clickhouse_status

```

If you try to make an endpoint or query in loop you will see an error. 

BTW i use code from [this pull request](https://github.com/long2ice/asynch/pull/29) to make ssl connection.

**Comment by long2ice** [comment]
I tried but on error without ssl

**Comment by denisov-vlad** [comment]
@long2ice I've updated to the latest dev branch after fix commit, and now I see the same error after 1st request. First request was ok but if you try to make ~ 5 requests after it you'll see ` Simultaneous queries on single connection detected` error.

The app above running with `WEB_CONCURRENCY=1` variable.

**Comment by gr8Adakron** [comment]
facing same issue, any resolutions?
