### ISSUE TITLE
with_column_types=True, but there are no column types

### ISSUE THREAD

**Issue by ghuname** [long2ice/asynch#4]
Why code:

```
import asyncio
from asynch import connect


async def main():
    conn = await connect(
        host="127.0.0.1",
        port=2714,
        database="default",
    )

    async with conn.cursor() as cursor:
        await cursor.execute("SELECT 1")
        ret = cursor.fetchone()
        print(ret)
		
		
loop = asyncio.get_event_loop()
loop.run_until_complete(asyncio.wait([main()]))
```

returns:
`(1,)`

with no column types?

In the line https://github.com/long2ice/asynch/blob/01f2502d8b22868d03996839625d6c3299bfcf3e/asynch/cursors.py#L61,  I can see with_column_types=True, but you are not returning them.

**Comment by ghuname** [comment]
@long2ice Can you please answer to this issue?

**Comment by long2ice** [comment]
Maybe bug there, PR is welcome

**Comment by ghuname** [comment]
Why you closed this issue?
