### ISSUE TITLE
AttributeError error of the fetchone function of the DictCursor class

### ISSUE THREAD

**Issue by Cooh12** [long2ice/asynch#88]
Hello! In version 0.2.2, the fetchone function raised an AttributeError error when row == None. In version 0.2.3, when row == None, {} is returned.
I would like to know the reason for this change. After the update, the logic in my application broke down.
Thank you in advance.
```python
class DictCursor(Cursor):
    async def fetchone(self):
        row = await super(DictCursor, self).fetchone()
        if self._columns and row:
            return dict(zip(self._columns, row))
        else:
            raise AttributeError("Not fould valid columns")
```
```python
async def fetchone(self):
        row = await super(DictCursor, self).fetchone()
        if self._columns:
            return dict(zip(self._columns, row)) if row else {}
        else:
            raise AttributeError("Invalid columns.")
```

**Comment by stankudrow** [comment]
@Cooh12 , hello, it was done here, I suppose - https://github.com/long2ice/asynch/compare/v0.2.2...v0.2.3#diff-a7386b71af40b83dd660607c7cc63d0c3593f6c9170b9cebecfd0b85d3a5144eR356-R376 . Do you have any pros about returning an empty container in lieu of `None` entity? Moreover, in what cases `None` should be returned?
